format = """
[┌─>](gray) \\[$username@$hostname:$directory\\] $conda $git_branch
[└─](gray)$character"""

[conda]
format = "[$symbol$environment]($style)"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style)"

[username]
format = "[$user]($style)"
style_user = "bold green"
show_always = true

[hostname]
format = "[$ssh_symbol$hostname]($style)"
style = "bold green"
ssh_only = false

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
style = "bold blue"
